services:
  db:
    image: postgres:15
    container_name: flashcard-db
    environment:
      POSTGRES_DB: flashcard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: flashcard-api
    ports:
      - "80:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432        
      - DB_NAME=flashcard
      - DB_USER=postgres
      - DB_PASSWORD=postgres

volumes:
  pgdata:
